version: '3.8'

volumes:
  db_storage:
  n8n_storage:

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_COMMUNITY_PACKAGES_ALLOW_USAGE=${N8N_COMMUNITY_PACKAGES_ALLOW_USAGE:-true}
      - N8N_EDITOR_BASE_URL=https://${NGROK_DOMAIN}
      - WEBHOOK_URL=https://${NGROK_DOMAIN}
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
      - N8N_HOST=${NGROK_DOMAIN}
      - N8N_PROTOCOL=https
      - NODE_ENV=production
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - ./n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 15s

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    depends_on:
      n8n:
        condition: service_healthy
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: http --domain=${NGROK_DOMAIN} n8n:5678 --log=stdout
    ports:
      - "4040:4040" # ngrok web UI (http://localhost:4040)
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c '</dev/tcp/localhost/4040' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s